// Generate .d.ts from Zod schemas in src/schemas.ts (TSX版)
import fs from 'fs/promises';
import path from 'path';

const outPath = path.join(process.cwd(), 'src/types/schemas.generated.d.ts');

function section(title: string): string {
	return `\n// === ${title} ===\n`;
}

const chunks: string[] = [];
chunks.push('// Auto-generated by scripts/gen_types.ts. Do NOT edit manually.');
chunks.push('/* eslint-disable */');
chunks.push("import type { z } from 'zod';");
chunks.push('import type {');
chunks.push('  CandleTypeEnum,');
chunks.push('  RenderChartSvgInputSchema,');
chunks.push('  RenderChartSvgOutputSchema,');
chunks.push('  ChartPayloadSchema,');
chunks.push('  GetIndicatorsDataSchema,');
chunks.push('  GetIndicatorsMetaSchema,');
chunks.push("} from '../schemas.js';");

// Enums and inputs
chunks.push(section('Enums & Inputs'));
chunks.push('export type CandleType = z.infer<typeof CandleTypeEnum>;');
chunks.push('export type RenderChartSvgInput = z.infer<typeof RenderChartSvgInputSchema>;');
chunks.push('export type RenderChartSvgOutput = z.infer<typeof RenderChartSvgOutputSchema>;');

// Indicators
chunks.push(section('Indicators DTOs'));
chunks.push('export type ChartPayloadFromSchema = z.infer<typeof ChartPayloadSchema>;');
chunks.push('export type GetIndicatorsDataFromSchema = z.infer<typeof GetIndicatorsDataSchema>;');
chunks.push('export type GetIndicatorsMetaFromSchema = z.infer<typeof GetIndicatorsMetaSchema>;');

const content = chunks.join('\n') + '\n';
await fs.mkdir(path.dirname(outPath), { recursive: true });
await fs.writeFile(outPath, content, 'utf8');
console.log(`Generated: ${path.relative(process.cwd(), outPath)}`);
