/**
 * gen_tool_list.ts — tool-registry.ts から全ツール一覧を読み取り
 * docs/tool-list.md を自動生成する。
 *
 * Usage: npx tsx scripts/gen_tool_list.ts
 */
import fs from 'node:fs';
import { allToolDefs } from '../src/tool-registry.js';

interface CategoryDef {
	label: string;
	names: Set<string>;
}

// tool-registry.ts のカテゴリ順に対応
const categories: CategoryDef[] = [
	{
		label: 'Data Retrieval（市場データ取得）',
		names: new Set([
			'get_ticker',
			'get_orderbook',
			'get_candles',
			'get_transactions',
			'get_flow_metrics',
			'get_volatility_metrics',
			'get_tickers_jpy',
		]),
	},
	{
		label: 'Technical Analysis（テクニカル分析）',
		names: new Set([
			'analyze_indicators',
			'analyze_bb_snapshot',
			'analyze_ichimoku_snapshot',
			'analyze_sma_snapshot',
			'analyze_ema_snapshot',
			'analyze_stoch_snapshot',
			'analyze_mtf_sma',
			'analyze_support_resistance',
			'analyze_candle_patterns',
			'analyze_volume_profile',
			'analyze_currency_strength',
			'analyze_fibonacci',
			'analyze_mtf_fibonacci',
		]),
	},
	{
		label: 'Signal & Detection（シグナル・パターン検出）',
		names: new Set(['analyze_market_signal', 'detect_patterns', 'detect_macd_cross', 'detect_whale_events']),
	},
	{
		label: 'Visualization（チャート描画）',
		names: new Set([
			'prepare_chart_data',
			'prepare_depth_data',
			'render_chart_svg',
			'render_depth_svg',
			'render_candle_pattern_diagram',
		]),
	},
	{
		label: 'Backtesting（バックテスト）',
		names: new Set(['run_backtest']),
	},
];

// Private tools（動的 import のため allToolDefs に含まれない場合がある）
const privateNames = [
	'get_my_assets',
	'get_my_trade_history',
	'get_my_orders',
	'analyze_my_portfolio',
	'get_my_deposit_withdrawal',
	'create_order',
	'cancel_order',
	'cancel_orders',
	'get_order',
	'get_orders_info',
];

function extractFirstLine(desc: string): string {
	// description の最初の行（[タグ] 部分を除去）
	const first = desc.split('\n')[0] ?? '';
	return first.replace(/^\[.*?\]\s*/, '').trim();
}

const lines: string[] = [];
lines.push('# Tool List');
lines.push('');
lines.push('> Auto-generated by `npx tsx scripts/gen_tool_list.ts`');
lines.push('');

const toolMap = new Map(allToolDefs.map((t) => [t.name, t]));

let publicCount = 0;

for (const cat of categories) {
	lines.push(`## ${cat.label}`);
	lines.push('');
	lines.push('| Tool | Description |');
	lines.push('|------|-------------|');

	for (const name of cat.names) {
		const tool = toolMap.get(name);
		if (tool) {
			lines.push(`| \`${tool.name}\` | ${extractFirstLine(tool.description)} |`);
			publicCount++;
		}
	}
	lines.push('');
}

// Private section
lines.push('## Private（要 API キー）');
lines.push('');
lines.push('`BITBANK_API_KEY` + `BITBANK_API_SECRET` 設定時のみ有効。');
lines.push('');
lines.push('| Tool | File |');
lines.push('|------|------|');
for (const name of privateNames) {
	// Private tools may not be loaded, so just list file paths
	lines.push(`| \`${name}\` | \`tools/private/${name}.ts\` |`);
}
lines.push('');

lines.push(`---`);
lines.push('');
lines.push(
	`Public: **${publicCount}** tools / Private: **${privateNames.length}** tools / Total: **${publicCount + privateNames.length}** tools`,
);
lines.push('');

const output = lines.join('\n');
const outPath = 'docs/tool-list.md';
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`Generated: ${outPath} (${publicCount} public + ${privateNames.length} private)`);
