/**
 * gen_tool_list.ts — tool-registry.ts から全ツール一覧を読み取り
 * docs/tool-list.md を自動生成する。
 *
 * Usage: npx tsx scripts/gen_tool_list.ts
 */
import fs from 'node:fs';
import { allToolDefs } from '../src/tool-registry.js';

interface CategoryDef {
	label: string;
	names: Set<string>;
}

// tool-registry.ts のカテゴリ順に対応
const categories: CategoryDef[] = [
	{
		label: 'Data Retrieval（市場データ取得）',
		names: new Set([
			'get_ticker',
			'get_orderbook',
			'get_candles',
			'get_transactions',
			'get_flow_metrics',
			'get_volatility_metrics',
			'get_tickers_jpy',
		]),
	},
	{
		label: 'Technical Analysis（テクニカル分析）',
		names: new Set([
			'analyze_indicators',
			'analyze_bb_snapshot',
			'analyze_ichimoku_snapshot',
			'analyze_sma_snapshot',
			'analyze_ema_snapshot',
			'analyze_stoch_snapshot',
			'analyze_mtf_sma',
			'analyze_support_resistance',
			'analyze_candle_patterns',
			'analyze_volume_profile',
			'analyze_currency_strength',
			'analyze_fibonacci',
			'analyze_mtf_fibonacci',
		]),
	},
	{
		label: 'Signal & Detection（シグナル・パターン検出）',
		names: new Set(['analyze_market_signal', 'detect_patterns', 'detect_macd_cross', 'detect_whale_events']),
	},
	{
		label: 'Visualization（チャート描画）',
		names: new Set([
			'prepare_chart_data',
			'prepare_depth_data',
			'render_chart_svg',
			'render_depth_svg',
			'render_candle_pattern_diagram',
		]),
	},
	{
		label: 'Data Quality（データ品質）',
		names: new Set(['validate_candle_data']),
	},
	{
		label: 'Backtesting（バックテスト）',
		names: new Set(['run_backtest']),
	},
];

// Private tools（動的 import のため allToolDefs に含まれない場合がある）
const privateNames = [
	// 口座情報
	'get_my_assets',
	'get_my_trade_history',
	'get_my_deposit_withdrawal',
	'analyze_my_portfolio',
	// 注文照会
	'get_my_orders',
	'get_order',
	'get_orders_info',
	// 取引操作（preview → execute）
	'preview_order',
	'create_order',
	'preview_cancel_order',
	'cancel_order',
	'preview_cancel_orders',
	'cancel_orders',
	// 信用取引
	'get_margin_status',
	'get_margin_positions',
	'get_margin_trade_history',
];

function extractFirstLine(desc: string): string {
	// description の最初の行（[タグ] 部分を除去）
	const first = desc.split('\n')[0] ?? '';
	return first.replace(/^\[.*?\]\s*/, '').trim();
}

const lines: string[] = [];
lines.push('# Tool List');
lines.push('');
lines.push('> Auto-generated by `npx tsx scripts/gen_tool_list.ts`');
lines.push('');

const toolMap = new Map(allToolDefs.map((t) => [t.name, t]));

// カテゴリ未登録のツールを検出（将来の追加漏れを防ぐ）
const categorizedNames = new Set<string>();
for (const cat of categories) for (const n of cat.names) categorizedNames.add(n);
const uncategorized = allToolDefs.map((t) => t.name).filter((n) => !categorizedNames.has(n));
if (uncategorized.length > 0) {
	console.error(`ERROR: Tools not assigned to any category: ${uncategorized.join(', ')}`);
	console.error('Add them to the `categories` list in scripts/gen_tool_list.ts.');
	process.exit(1);
}

// Private ツールのファイル存在チェック（tools/private/*.ts と privateNames が一致するか）
const privateDir = 'tools/private';
const privateFiles = fs
	.readdirSync(privateDir)
	.filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
	.map((f) => f.replace(/\.ts$/, ''));
const missingInList = privateFiles.filter((f) => !privateNames.includes(f));
const missingInFiles = privateNames.filter((n) => !privateFiles.includes(n));
if (missingInList.length > 0 || missingInFiles.length > 0) {
	if (missingInList.length > 0) {
		console.error(`ERROR: Private tool files not in privateNames: ${missingInList.join(', ')}`);
	}
	if (missingInFiles.length > 0) {
		console.error(`ERROR: privateNames entries with no file: ${missingInFiles.join(', ')}`);
	}
	console.error('Update `privateNames` in scripts/gen_tool_list.ts to match tools/private/*.ts.');
	process.exit(1);
}

let publicCount = 0;

for (const cat of categories) {
	lines.push(`## ${cat.label}`);
	lines.push('');
	lines.push('| Tool | Description |');
	lines.push('|------|-------------|');

	for (const name of cat.names) {
		const tool = toolMap.get(name);
		if (tool) {
			lines.push(`| \`${tool.name}\` | ${extractFirstLine(tool.description)} |`);
			publicCount++;
		}
	}
	lines.push('');
}

// Private section
lines.push('## Private（要 API キー）');
lines.push('');
lines.push('`BITBANK_API_KEY` + `BITBANK_API_SECRET` 設定時のみ有効。');
lines.push('');
lines.push('| Tool | File |');
lines.push('|------|------|');
for (const name of privateNames) {
	// Private tools may not be loaded, so just list file paths
	lines.push(`| \`${name}\` | \`tools/private/${name}.ts\` |`);
}
lines.push('');

lines.push(`---`);
lines.push('');
lines.push(
	`Public: **${publicCount}** tools / Private: **${privateNames.length}** tools / Total: **${publicCount + privateNames.length}** tools`,
);
lines.push('');

const output = lines.join('\n');
const outPath = 'docs/tool-list.md';
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`Generated: ${outPath} (${publicCount} public + ${privateNames.length} private)`);
